# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/matt154/Documents/vansim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/matt154/Documents/vansim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/matt154/Documents/vansim/CMakeFiles /Users/matt154/Documents/vansim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/matt154/Documents/vansim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vansim

# Build rule for target.
vansim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vansim
.PHONY : vansim

# fast build rule for target.
vansim/fast:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/build
.PHONY : vansim/fast

src/Agent.o: src/Agent.cpp.o

.PHONY : src/Agent.o

# target to build an object file
src/Agent.cpp.o:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/Agent.cpp.o
.PHONY : src/Agent.cpp.o

src/Agent.i: src/Agent.cpp.i

.PHONY : src/Agent.i

# target to preprocess a source file
src/Agent.cpp.i:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/Agent.cpp.i
.PHONY : src/Agent.cpp.i

src/Agent.s: src/Agent.cpp.s

.PHONY : src/Agent.s

# target to generate assembly for a file
src/Agent.cpp.s:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/Agent.cpp.s
.PHONY : src/Agent.cpp.s

src/GossipAgent.o: src/GossipAgent.cpp.o

.PHONY : src/GossipAgent.o

# target to build an object file
src/GossipAgent.cpp.o:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/GossipAgent.cpp.o
.PHONY : src/GossipAgent.cpp.o

src/GossipAgent.i: src/GossipAgent.cpp.i

.PHONY : src/GossipAgent.i

# target to preprocess a source file
src/GossipAgent.cpp.i:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/GossipAgent.cpp.i
.PHONY : src/GossipAgent.cpp.i

src/GossipAgent.s: src/GossipAgent.cpp.s

.PHONY : src/GossipAgent.s

# target to generate assembly for a file
src/GossipAgent.cpp.s:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/GossipAgent.cpp.s
.PHONY : src/GossipAgent.cpp.s

src/GossipSession.o: src/GossipSession.cpp.o

.PHONY : src/GossipSession.o

# target to build an object file
src/GossipSession.cpp.o:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/GossipSession.cpp.o
.PHONY : src/GossipSession.cpp.o

src/GossipSession.i: src/GossipSession.cpp.i

.PHONY : src/GossipSession.i

# target to preprocess a source file
src/GossipSession.cpp.i:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/GossipSession.cpp.i
.PHONY : src/GossipSession.cpp.i

src/GossipSession.s: src/GossipSession.cpp.s

.PHONY : src/GossipSession.s

# target to generate assembly for a file
src/GossipSession.cpp.s:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/GossipSession.cpp.s
.PHONY : src/GossipSession.cpp.s

src/Network.o: src/Network.cpp.o

.PHONY : src/Network.o

# target to build an object file
src/Network.cpp.o:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/Network.cpp.o
.PHONY : src/Network.cpp.o

src/Network.i: src/Network.cpp.i

.PHONY : src/Network.i

# target to preprocess a source file
src/Network.cpp.i:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/Network.cpp.i
.PHONY : src/Network.cpp.i

src/Network.s: src/Network.cpp.s

.PHONY : src/Network.s

# target to generate assembly for a file
src/Network.cpp.s:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/Network.cpp.s
.PHONY : src/Network.cpp.s

src/World.o: src/World.cpp.o

.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i

.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s

.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/vansim.dir/build.make CMakeFiles/vansim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... vansim"
	@echo "... src/Agent.o"
	@echo "... src/Agent.i"
	@echo "... src/Agent.s"
	@echo "... src/GossipAgent.o"
	@echo "... src/GossipAgent.i"
	@echo "... src/GossipAgent.s"
	@echo "... src/GossipSession.o"
	@echo "... src/GossipSession.i"
	@echo "... src/GossipSession.s"
	@echo "... src/Network.o"
	@echo "... src/Network.i"
	@echo "... src/Network.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

